function [feasibilityState] = scheme1_SCP_CheckFeasibility(timeRatio, powerMatInit,P_S,P_R,N,gammaSRT,gammaRDT,gammaSDT,gammaRRT)
%scheme1_SCP SCP algorithm aa
%   powerMat: optimal power allocation
%   cvx_optval: optimal value of cvx

cvx_begin quiet
cvx_solver Mosek_2
   variable powerMat(3,2*N)
   expression cons
   cons = 0;
   for ii = 1:N
      cons = timeRatio*(-log(1 + powerMat(2,2*ii-1)*gammaSRT(ii) + powerMat(3,2*ii-1)*gammaRRT(ii))...
          - log(1+ (powerMat(1,2*ii-1) + powerMat(2,2*ii-1))*gammaSDT(ii) + powerMat(3,2*ii-1)*gammaRDT(ii))...
          + log(1 + (powerMatInit(1,2*ii-1) + powerMatInit(2,2*ii-1))*gammaSRT(ii) + powerMatInit(3,2*ii-1)*gammaRRT(ii))...
          + log(1 + (powerMatInit(1,2*ii-1) + powerMatInit(2,2*ii-1))*gammaSDT(ii))...
          + (gammaSRT(ii)/(1 + (powerMatInit(1,2*ii-1) + powerMatInit(2,2*ii-1))*gammaSRT(ii) + powerMatInit(3,2*ii-1)*gammaRRT(ii))...
          + gammaSDT(ii)/(1 + (powerMatInit(1,2*ii-1) + powerMatInit(2,2*ii-1))*gammaSDT(ii)))*(powerMat(1,2*ii-1) - powerMatInit(1,2*ii-1))...
          + (gammaSRT(ii)/(1 + (powerMatInit(1,2*ii-1) + powerMatInit(2,2*ii-1))*gammaSRT(ii) + powerMatInit(3,2*ii-1)*gammaRRT(ii))...
          + gammaSDT(ii)/(1 + (powerMatInit(1,2*ii-1) + powerMatInit(2,2*ii-1))*gammaSDT(ii)))*(powerMat(2,2*ii-1) - powerMatInit(2,2*ii-1))...
          + gammaRRT(ii)/(1 + (powerMatInit(1,2*ii-1) + powerMatInit(2,2*ii-1))*gammaSRT(ii) + powerMatInit(3,2*ii-1)*gammaRRT(ii))...
          *(powerMat(3,2*ii-1) - powerMatInit(3,2*ii-1)))...
          +(1-timeRatio)*(-log(1 + powerMat(2,2*ii)*gammaSRT(ii) + powerMat(3,2*ii)*gammaRRT(ii))...
          - log(1+ (powerMat(1,2*ii) + powerMat(2,2*ii))*gammaSDT(ii) + powerMat(3,2*ii)*gammaRDT(ii))...
          + log(1 + (powerMatInit(1,2*ii) + powerMatInit(2,2*ii))*gammaSRT(ii) + powerMatInit(3,2*ii)*gammaRRT(ii))...
          + log(1 + (powerMatInit(1,2*ii) + powerMatInit(2,2*ii))*gammaSDT(ii))...
          + (gammaSRT(ii)/(1 + (powerMatInit(1,2*ii) + powerMatInit(2,2*ii))*gammaSRT(ii) + powerMatInit(3,2*ii)*gammaRRT(ii))...
          + gammaSDT(ii)/(1 + (powerMatInit(1,2*ii) + powerMatInit(2,2*ii))*gammaSDT(ii)))*(powerMat(1,2*ii) - powerMatInit(1,2*ii))...
          + (gammaSRT(ii)/(1 + (powerMatInit(1,2*ii) + powerMatInit(2,2*ii))*gammaSRT(ii) + powerMatInit(3,2*ii)*gammaRRT(ii))...
          + gammaSDT(ii)/(1 + (powerMatInit(1,2*ii) + powerMatInit(2,2*ii))*gammaSDT(ii)))*(powerMat(2,2*ii) - powerMatInit(2,2*ii))...
          + gammaRRT(ii)/(1 + (powerMatInit(1,2*ii) + powerMatInit(2,2*ii))*gammaSRT(ii) + powerMatInit(3,2*ii)*gammaRRT(ii))...
          *(powerMat(3,2*ii) - powerMatInit(3,2*ii)))+ cons;
   end
   minimize 1
   subject to
       cons <= 0
       sum(sum(timeRatio.*powerMat(1:2,1:2:2*N) + (1-timeRatio).*powerMat(1:2,2:2:2*N))) <= P_S
       sum(sum(timeRatio.*powerMat(3,1:2:2*N) + (1-timeRatio).*powerMat(3,2:2:2*N))) <= P_R
       powerMat >= 0
cvx_end
if cvx_status(1) == 'S'
    feasibilityState = 1;
else
    feasibilityState = 0;
end
end

