function [rate] = scheme1_rate(timeRatio,powerMat,N,gammaSRT,gammaRDT,gammaSDT,gammaRRT)
%scheme1_rate 
obj = 0;
for ii = 1:N
  obj = timeRatio.*(-log(1 + powerMat(1,2*ii-1)*gammaSRT(ii) + powerMat(2,2*ii-1)*gammaSRT(ii)...
      + powerMat(3,2*ii-1)*gammaRRT(ii)) - log(1 + powerMat(2,2*ii-1)*gammaSDT(ii))...
      + log(1 + powerMat(2,2*ii-1)*gammaSRT(ii) + powerMat(3,2*ii-1)*gammaRRT(ii)))...
      + (1 - timeRatio).*(-log(1 + powerMat(1,2*ii)*gammaSRT(ii) + powerMat(2,2*ii)*gammaSRT(ii)...
      + powerMat(3,2*ii)*gammaRRT(ii)) - log(1 + powerMat(2,2*ii)*gammaSDT(ii))...
      + log(1 + powerMat(2,2*ii)*gammaSRT(ii) + powerMat(3,2*ii)*gammaRRT(ii)))...
      + obj;
end
rate = -obj./N./log(2);
end


